In [1]:
import numpy as np

In [2]:
#Bir NumPy dizisi oluşturur.

arr = np.array([1, 2, 3, 4])
print(arr)

[1 2 3 4]


In [3]:
#Belirli bir aralıktaki sayılardan bir dizi oluşturur

arr = np.arange(0, 10, 2)
print(arr)

[0 2 4 6 8]


In [4]:
#Verilen boyutlarda sıfırlardan oluşan bir dizi oluşturur.

arr = np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [5]:
#Verilen boyutlarda birlerden oluşan bir dizi oluşturur.

arr = np.ones(3)
print(arr)

[1. 1. 1.]


In [6]:
#Belirli bir aralıkta eşit aralıklı sayılar içeren bir dizi oluşturur.

arr = np.linspace(0, 10, 5)
print(arr)

[ 0.   2.5  5.   7.5 10. ]


In [7]:
#Bir dizinin şekil (boyut) değişimini yapar.

arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape(2, 3)
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [8]:
#Çok boyutlu bir diziyi tek boyutlu hale getirir.

arr = np.array([[1, 2], [3, 4]])
flattened = arr.flatten()
print(flattened)

[1 2 3 4]


In [9]:
#Bir dizinin elemanlarının toplamını hesaplar.

arr = np.array([1, 2, 3, 4])
total = np.sum(arr)
print(total)

10


In [10]:
#Bir dizinin ortalamasını hesaplar.

arr = np.array([1, 2, 3, 4])
mean_value = np.mean(arr)
print(mean_value)

2.5


In [11]:
#Bir dizinin medyanını hesaplar.

arr = np.array([1, 3, 2, 4])
median_value = np.median(arr)
print(median_value)

2.5
